(() => {
"use strict";
const $=s=>document.querySelector(s);
const screens={title:$("#title"),select:$("#select"),battle:$("#battle"),result:$("#result")};
const chars=[
{id:"ren",name:"REN CROSS",jp:"レン・クロス",type:"BALANCE",typejp:"バランス型",age:17,height:172,weapon:"BLADE",attack:30,c:"#1684ff",soft:"#1684ff33",quote:"守るために、強くなる。それだけだ。",unique:{id:"overblade",name:"オーバーブレード",short:"O",kind:"overblade",cd:5000,c:"#27e8ff",desc:"次の攻撃を+50。"}},
{id:"kai",name:"KAI VERDE",jp:"カイ・ヴェルド",type:"SPEED",typejp:"スピード型",age:16,height:170,weapon:"KNIFE",attack:20,c:"#9cff24",soft:"#9cff2433",quote:"俺は止まらない。一歩先、そこにだけ勝ちがある。",unique:{id:"accelstep",name:"アクセルステップ",short:"A",kind:"accel",cd:2200,c:"#9cff24",desc:"2マス移動。次の攻撃+10。"}}
];
const common=[
{id:"sword",name:"ソード",short:"S",kind:"attack",damage:40,range:1,cd:900,c:"#ff9f24",desc:"前方1マスに40ダメージ。"},
{id:"shot",name:"ショット",short:"S",kind:"attack",damage:20,range:3,cd:800,c:"#28a8ff",desc:"前方3マスに20ダメージ。"},
{id:"shield",name:"シールド",short:"G",kind:"shield",cd:1400,c:"#6dff8e",desc:"次のダメージを50%軽減。"},
{id:"dash",name:"ダッシュ",short:"D",kind:"dash",distance:2,cd:1200,c:"#ff9d20",desc:"前方2マス移動。"},
{id:"recover",name:"リカバー",short:"R",kind:"heal",heal:30,cd:1800,c:"#42ff9b",desc:"HPを30回復。"}
];
let state={char:null,b:null,selected:null,timer:null,ai:null};
const show=n=>Object.keys(screens).forEach(k=>screens[k].hidden=k!==n);
const distance=(a,b)=>Math.abs(a.r-b.r)+Math.abs(a.c-b.c);
const inBounds=(r,c)=>r>=0&&r<5&&c>=0&&c<5;
const direction=(dr,dc)=>dr===-1?"up":dr===1?"down":dc===-1?"left":dc===1?"right":null;
const facing=(a,b,f,range)=>{let dr=b.r-a.r,dc=b.c-a.c;return f==="up"?dc===0&&dr<0&&-dr<=range:f==="down"?dc===0&&dr>0&&dr<=range:f==="left"?dr===0&&dc<0&&-dc<=range:f==="right"?dr===0&&dc>0&&dc<=range:false};
const stepPos=(p,f,n)=>{const d={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]}[f];return{r:p.r+d[0]*n,c:p.c+d[1]*n}};
const all=()=>[state.char.unique,...common];
const svgFor=c=>c.id==="ren"?"ren-idle.svg":"kai-idle.svg";
function log(t,k=""){const e=document.createElement("div");e.className="entry "+k;e.textContent=t;$("#log").prepend(e)}
function msg(t){$("#msg").textContent=t}
function time(ms){let s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function renderChars(){const box=$("#chars");box.innerHTML="";chars.forEach(c=>{const a=document.createElement("article");a.className="char panel";a.style.setProperty("--accent",c.c);a.style.setProperty("--soft",c.soft);a.innerHTML=`<div class="char-art"><img src="${svgFor(c)}" alt="${c.name}"></div><div class="eyebrow">${c.type} / ${c.weapon}</div><h2>${c.name}</h2><small>${c.jp} — ${c.typejp}</small><p class="quote">「${c.quote}」</p><div class="stats"><div>AGE<b>${c.age}</b></div><div>HEIGHT<b>${c.height}cm</b></div><div>NORMAL ATK<b>${c.attack}</b></div><div>ABILITY<b>${c.id==="ren"?"OVERDRIVE":"STEP"}</b></div></div><footer><span>UNIQUE: ${c.unique.name}</span><button class="cyber" type="button">SELECT</button></footer>`;a.onclick=()=>start(c);box.appendChild(a)})}
function start(c){stop();state.char=c;state.selected=null;state.b={status:"playing",started:performance.now(),elapsed:0,turn:1,p:{r:4,c:2,hp:100,f:"up",shield:false,bonus:0,next:0,step:false,cd:{}},e:{r:0,c:2,hp:100,f:"down",cd:0,move:0}};$("#log").innerHTML="";show("battle");log("BATTLE START");msg("隣接するマスをタップして移動。");renderAll();state.timer=requestAnimationFrame(tick);state.ai=setInterval(ai,900)}
function stop(){if(state.timer)cancelAnimationFrame(state.timer);if(state.ai)clearInterval(state.ai);state.timer=null;state.ai=null}
function tick(){const b=state.b;if(!b||b.status!=="playing")return;b.elapsed=performance.now()-b.started;const nt=Math.floor(b.elapsed/5000)+1;if(nt!==b.turn){b.turn=nt;if(state.char.id==="kai"){b.p.step=false;b.p.bonus=0;log("KAI STEP RESET")}}renderAll();state.timer=requestAnimationFrame(tick)}
function renderAll(){const b=state.b;if(!b)return;$("#pn").textContent=state.char.name.split(" ")[0];$("#pt").textContent=state.char.type;$("#pht").textContent=`${b.p.hp} / 100`;$("#eht").textContent=`${b.e.hp} / 100`;$("#phb").style.width=b.p.hp+"%";$("#ehb").style.width=b.e.hp+"%";$("#turn").textContent="TURN "+String(b.turn).padStart(2,"0");$("#time").textContent=time(b.elapsed);$("#face").textContent=b.p.f.toUpperCase();$("#pst").textContent=state.char.id==="ren"&&b.p.hp<=30?"OVERDRIVE ACTIVE":b.p.shield?"SHIELD ACTIVE":"READY";$("#est").textContent=b.e.hp<=0?"DESTROYED":"SEARCHING";$("#dist").textContent=distance(b.p,b.e);const ch=all().find(q=>q.id===state.selected);$("#next").textContent=ch?ch.name.toUpperCase():"MOVE";renderGrid();renderChips()}
function renderGrid(){const g=$("#grid"),b=state.b;g.innerHTML="";for(let r=0;r<5;r++)for(let c=0;c<5;c++){const x=document.createElement("button");x.type="button";x.className="cell "+(r>=3?"playerzone":"enemyzone")+(r===2?" boundary":"");x.dataset.r=r;x.dataset.c=c;const d=distance(b.p,{r,c}),ep=r===b.e.r&&c===b.e.c,pp=r===b.p.r&&c===b.p.c;if(!pp&&!ep&&d===1)x.classList.add("move");const ch=all().find(q=>q.id===state.selected);if(ep&&ch?.kind==="attack"&&facing(b.p,b.e,b.p.f,ch.range))x.classList.add("range");x.innerHTML=`<span class="coord">${r+1}-${c+1}</span>`;if(pp)x.innerHTML+=`<span class="ring"></span><span class="actor"><img src="${svgFor(state.char)}"></span>`;if(ep)x.innerHTML+=`<span class="ring"></span><span class="actor enemyactor"><img src="cpu.svg"></span>`;x.onclick=cellClick;g.appendChild(x)}}
function renderChips(){const box=$("#chiplist");box.innerHTML="";all().forEach(ch=>{const rem=Math.max(0,(state.b.p.cd[ch.id]||0)-performance.now()),x=document.createElement("button");x.type="button";x.className="chip "+(state.selected===ch.id?"sel ":"")+(rem?"off":"");x.style.setProperty("--c",ch.c);x.innerHTML=`<span class="meta">${rem?(rem/1000).toFixed(1)+"s":"READY"}</span><div class="icon">${ch.short}</div><div class="chipname">${ch.name}</div><div class="desc">${ch.desc}</div>`;x.onclick=()=>{if(rem)return;if(ch.kind==="shield"||ch.kind==="heal"){useChip(ch);return}state.selected=state.selected===ch.id?null:ch.id;renderAll();$("#chipmode").textContent=state.selected?ch.name+" SELECTED — TARGET":"Choose an action"};box.appendChild(x)})}
function damage(side,n,src){const t=state.b[side];let v=n;if(side==="p"&&t.shield){v=Math.ceil(v*.5);t.shield=false;log("SHIELD REDUCED DAMAGE","good")}t.hp=Math.max(0,t.hp-v);log(src+" → "+v+" DAMAGE","damage");win()}
function normalAttack(){const b=state.b;if(!facing(b.p,b.e,b.p.f,1)){msg("射程外。敵が前方1マスにいる必要があります。");log("NORMAL ATTACK — OUT OF RANGE","warn");return}const n=state.char.attack+b.p.bonus+b.p.next;b.p.bonus=0;b.p.next=0;damage("e",n,"NORMAL ATTACK");if(state.char.id==="kai"){b.p.step=true;msg("KAI STEP READY — 攻撃後に1マス移動可能。");log("KAI STEP AVAILABLE","good")}}
function moveTo(r,c){const b=state.b;if(distance(b.p,{r,c})!==1){msg("移動距離が長すぎます。1マスずつ移動してください。");log("MOVE BLOCKED — TOO FAR","warn");return}if(r===b.e.r&&c===b.e.c){msg("敵のマスには移動できません。");return}const dr=r-b.p.r,dc=c-b.p.c;b.p.f=direction(dr,dc)||b.p.f;b.p.r=r;b.p.c=c;log(state.char.id.toUpperCase()+" MOVED");msg("移動完了。")}
function useChip(ch){const b=state.b;if((b.p.cd[ch.id]||0)>performance.now()){msg("クールダウン中です。");return}if(ch.kind==="attack"){if(!facing(b.p,b.e,b.p.f,ch.range)){msg("射程外。");log(ch.name+" — OUT OF RANGE","warn");return}const n=ch.damage+b.p.bonus+b.p.next;b.p.bonus=0;b.p.next=0;damage("e",n,ch.name.toUpperCase())}else if(ch.kind==="shield"){b.p.shield=true;log("SHIELD ACTIVE","good");msg("次のダメージを50%軽減。")}else if(ch.kind==="heal"){const old=b.p.hp;b.p.hp=Math.min(100,b.p.hp+30);log("RECOVER +"+(b.p.hp-old)+" HP","good")}else if(ch.kind==="dash"||ch.kind==="accel"){const p=stepPos(b.p,b.p.f,2);if(!inBounds(p.r,p.c)||p.r===b.e.r&&p.c===b.e.c){msg("その方向には移動できません。");return}b.p.r=p.r;b.p.c=p.c;if(ch.kind==="accel")b.p.bonus=10;log(ch.name.toUpperCase()+" — 2 SQUARES","good");msg(ch.kind==="accel"?"2マス移動。次の攻撃+10。":"2マスダッシュ。")}else if(ch.kind==="overblade"){b.p.next+=50;log("OVER BLADE — NEXT ATTACK +50","good");msg("次の攻撃が+50。")}b.p.cd[ch.id]=performance.now()+ch.cd;state.selected=null;renderAll();win()}
function cellClick(e){const b=state.b,r=+e.currentTarget.dataset.r,c=+e.currentTarget.dataset.c,ep=r===b.e.r&&c===b.e.c,ch=all().find(q=>q.id===state.selected);$("#dist").textContent=distance(b.p,{r,c});if(ch){if(ch.kind==="attack"&&ep)useChip(ch);else if(ch.kind==="dash"||ch.kind==="accel"||ch.kind==="overblade")useChip(ch);else msg("このチップは対象指定不要です。");return}if(ep){normalAttack();return}if(state.char.id==="kai"&&b.p.step&&distance(b.p,{r,c})===1){const dr=r-b.p.r,dc=c-b.p.c;b.p.f=direction(dr,dc)||b.p.f;b.p.r=r;b.p.c=c;b.p.step=false;log("KAI STEP — 1 SQUARE","good");msg("ステップ移動。");renderAll();return}moveTo(r,c);renderAll()}
function ai(){const b=state.b;if(!b||b.status!=="playing")return;const d=distance(b.e,b.p);if(facing(b.e,b.p,b.e.f,1)){damage("p",15,"CPU ATTACK");return}if(d<=1)return;const options=[{r:b.e.r+Math.sign(b.p.r-b.e.r),c:b.e.c},{r:b.e.r,c:b.e.c+Math.sign(b.p.c-b.e.c)}].filter(p=>inBounds(p.r,p.c)&&!(p.r===b.p.r&&p.c===b.p.c));const q=options.find(p=>distance(p,b.p)<d);if(q){b.e.f=direction(b.p.r-b.e.r,b.p.c-b.e.c)||b.e.f;b.e.r=q.r;b.e.c=q.c;log("CPU MOVED");renderAll()}}
function win(){const b=state.b;if(b.e.hp<=0)end("victory");else if(b.p.hp<=0)end("defeat")}
function end(r){state.b.status=r;stop();$("#resultlabel").textContent=r==="victory"?"VICTORY":"DEFEAT";$("#resultlabel").className="resultlabel "+r;$("#summary").textContent=r==="victory"?"ENEMY UNIT DESTROYED.":"SWEEPER UNIT DOWN.";$("#rc").textContent=state.char.name.split(" ")[0];$("#rt").textContent=time(state.b.elapsed);$("#rh").textContent=state.b.hp;show("result")}
$("#new").onclick=()=>show("select");$("#clear").onclick=()=>{state.selected=null;renderAll()};$("#rematch").onclick=()=>start(state.char);$("#titlebtn").onclick=()=>{stop();show("title")};renderChars();show("title");
window.addEventListener("error",e=>console.error("[SWEEPER]",e.error||e.message));window.addEventListener("unhandledrejection",e=>console.error("[SWEEPER]",e.reason));
})();